name: 'Tomorrow, Today.'
favicon: null
layout_spectrum: 0.66645
typography_spectrum: 0.78815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b3d0f1'
    - '#7087b8'
    - '#5c9bd4'
    - '#9cb2c5'
    - '#53b6e6'
  brandStrength: 0.6070529285352677
  lightness: 0.6750714958179742
  saturation: 0.6153222382999957
  rhythmicContrast: 0.7600785959511995
purpose: []
