name: 'Tomorrow, Today.'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6194743
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00001c'
    - '#ffffdd'
    - '#ff5f2b'
    - '#ffc836'
    - '#876178'
  brandStrength: 0.6070529285352677
  lightness: 0.6750715
  saturation: 0.8727598
  rhythmicContrast: 0.7234169
purpose: []
